_wandb:
    value:
        cli_version: 0.22.3
        e:
            41fw5k294ydez0jely147frclu6iwbc1:
                args:
                    - --epochs
                    - "2"
                codePath: train.py
                codePathLocal: train.py
                cpu_count: 4
                cpu_count_logical: 8
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "52521566208"
                        used: "24701521920"
                email: pes1ug23am257@pesu.pes.edu
                executable: /home/sai/miniconda3/envs/collegeML/bin/python3
                git:
                    commit: 9d67de03efb168216994737bef5f4707f16d664a
                    remote: https://github.com/S-Sairam/sam-optimizer
                gpu: NVIDIA GeForce GTX 1650
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Turing
                      cudaCores: 896
                      memoryTotal: "4294967296"
                      name: NVIDIA GeForce GTX 1650
                      uuid: GPU-19db2347-180d-e740-184e-41a8d239ce15
                host: archlinux
                memory:
                    total: "8180408320"
                os: Linux-6.16.8-arch3-1-x86_64-with-glibc2.42
                program: /home/sai/Projects/sam-optimizer/train.py
                python: CPython 3.10.18
                root: /home/sai/Projects/sam-optimizer
                startedAt: "2025-10-30T03:35:38.434410Z"
                writerId: 41fw5k294ydez0jely147frclu6iwbc1
        m: []
        python_version: 3.10.18
        t:
            "1":
                - 1
                - 41
                - 105
            "2":
                - 1
                - 41
                - 105
            "3":
                - 16
            "4": 3.10.18
            "5": 0.22.3
            "12": 0.22.3
            "13": linux-x86_64
batch_size:
    value: 128
epochs:
    value: 2
learning_rate:
    value: 0.1
